services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - webnet

  mongodb:
    container_name: database_container
    image: mongo
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    networks:
      - webnet

networks:
  webnet:
