FROM node:20.11.1-alpine
WORKDIR /src/app

COPY package*.json ./
RUN npm install --production

COPY . .
EXPOSE 3000
ENV PORT=3000
ENV MAIL_SERVER=smtp.gmail.com
ENV MAIL_USERNAME=tiendat79197@gmail.com
ARG MAIL_PASSWORD
ENV MAIL_PASSWORD=${MAIL_PASSWORD}
ENV MAIL_PORT=587
ENV MAIL_SSL=False
ENV MAIL_TLS=True
ENV CLIENT_ID=AfqyHnzZEZIZwM9lRyIWs_TyukXIWxbTW9Kv39eCPk_0Ox51oJgdgWmo33FNqZ85X2LPlpEYYCpVZM2a
ENV CLIENT_SECRET=EPMUbX_5oB4yRN1WtPfU1eIkPuaFkOJXUvqAv-RBBVcqcl4maV_WMDy-YmTHvFypd95YW7BzISRePOCM
ENV PAYPAL_EMAIL=sb-8l3gr31077380@personal.example.com
ENV PAYPAL_PWD=%HJ2vX=z

CMD ["npm", "start"]
