services:
  app:
    build: .
    ports:
      - ":3000"
    depends_on:
      - mongodb
      - redis
    deploy:
     replicas: 3
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - webnet

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - webnet

  mongodb:
    container_name: database_container
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    networks:
      - webnet

volumes:
  mongodb_data:
    driver: local
networks:
  webnet:
